version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    networks:
      - node-network
      
  node-api-tpdweb:
    build: .
    image: node-api-tpdweb
    container_name: node-api-tpdweb
    ports:
      - '8000:3000'
    depends_on:
      - mongodb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge